In [2]:
import numpy as np
import pandas as pd

<h1><b>1. Khám phá dữ liệu (đan xen với tiền xử lý dữ liệu)</b></h1>

### Đọc dữ liệu từ tập tin (file)

Đầu tiên, đọc dữ liệu từ file "kaggle_survey_2022_responses.csv" và lưu kết quả vào DataFrame df.

In [3]:
df_1 = pd.read_csv("kaggle_survey_2022_responses.csv")
df_1.head(5)

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/4031676807.py:1: DtypeWarning: Columns (0,208,225,255,257,260,270,271,277) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1 = pd.read_csv("kaggle_survey_2022_responses.csv")

,Duration (in seconds),Q2,Q3,Q4,Q5,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,...,Q44_3,Q44_4,Q44_5,Q44_6,Q44_7,Q44_8,Q44_9,Q44_10,Q44_11,Q44_12
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,"Are you currently a student? (high school, uni...",On which platforms have you begun or completed...,On which platforms have you begun or completed...,On which platforms have you begun or completed...,On which platforms have you begun or completed...,On which platforms have you begun or completed...,...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...,Who/what are your favorite media sources that ...
1,121,30-34,Man,India,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,462,30-34,Man,Algeria,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,293,18-21,Man,Egypt,Yes,Coursera,edX,NaN,DataCamp,NaN,...,NaN,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...","Podcasts (Chai Time Data Science, O’Reilly Dat...",NaN,NaN,NaN,NaN,NaN
4,851,55-59,Man,France,No,Coursera,NaN,Kaggle Learn Courses,NaN,NaN,...,NaN,"Kaggle (notebooks, forums, etc)","Course Forums (forums.fast.ai, Coursera forums...",NaN,NaN,"Blogs (Towards Data Science, Analytics Vidhya,...",NaN,NaN,NaN,NaN

In [4]:
df_1.shape

(23998, 296)

## Tiền xử lý dữ liệu để đưa về dạng có thể phân tích

DÒng đầu tiên là câu hỏi, ta sẽ lấy dòng này lưu vào `dic_question` và xoá dòng này đi

In [5]:
dic_question = dict(df_1.iloc[0,:])
df_1 = df_1.drop(0)

Chuyển `dic_question` thành `new_dic` bằng việc bỏ những câu hỏi trùng nhau

In [6]:
new_dic = dict()
for i in dic_question.keys():
    i1 = i + ' '
    
    if '_1 ' in i1:
        if "?" in dic_question[i]:
            new_dic[i[0:i.index("_")]] = dic_question[i][0:dic_question[i].index('?')+1]
        elif ":" in dic_question[i]: 
            new_dic[i[0:i.index("_")]] = dic_question[i][0:dic_question[i].index(':')]
        else:
            new_dic[i[0:i.index("_")]] = dic_question[i]
    elif '_' not in i:
        if "?" in dic_question[i]:
            new_dic[i] = dic_question[i][0:dic_question[i].index('?')+1]
        elif ":" in dic_question[i]: 
            new_dic[i] = dic_question[i][0:dic_question[i].index(':')]
        else:
            new_dic[i] = dic_question[i]
new_dic['Duration (in seconds)'] = 'Duration'
new_dic

{'Duration (in seconds)': 'Duration',
 'Q2': 'What is your age (# years)?',
 'Q3': 'What is your gender?',
 'Q4': 'In which country do you currently reside?',
 'Q5': 'Are you currently a student?',
 'Q6': 'On which platforms have you begun or completed data science courses?',
 'Q7': 'What products or platforms did you find to be most helpful when you first started studying data science?',
 'Q8': 'What is the highest level of formal education that you have attained or plan to attain within the next 2 years?',
 'Q9': 'Have you ever published any academic research (papers, preprints, conference proceedings, etc)?',
 'Q10': 'Did your research make use of machine learning?',
 'Q11': 'For how many years have you been writing code and/or programming?',
 'Q12': 'What programming languages do you use on a regular basis?',
 'Q13': "Which of the following integrated development environments (IDE's) do you use on a regular basis?",
 'Q14': 'Do you use any of the following hosted notebook products?',
 'Q15': 'Do you use any of the following data visualization libraries on a regular basis?',
 'Q16': 'For how many years have you used machine learning methods?',
 'Q17': 'Which of the following machine learning frameworks do you use on a regular basis?',
 'Q18': 'Which of the following ML algorithms do you use on a regular basis?',
 'Q19': 'Which categories of computer vision methods do you use on a regular basis?',
 'Q20': 'Which of the following natural language processing (NLP) methods do you use on a regular basis?',
 'Q21': 'Do you download pre-trained model weights from any of the following services?',
 'Q22': 'Which of the following ML model hubs/repositories do you use most often?',
 'Q23': 'Select the title most similar to your current role (or most recent title if retired)',
 'Q24': 'In what industry is your current employer/contract (or your most recent employer if retired)?',
 'Q25': 'What is the size of the company where you are employed?',
 'Q26': 'Approximately how many individuals are responsible for data science workloads at your place of business?',
 'Q27': 'Does your current employer incorporate machine learning methods into their business?',
 'Q28': 'Select any activities that make up an important part of your role at work',
 'Q29': 'What is your current yearly compensation (approximate $USD)?',
 'Q30': 'Approximately how much money have you spent on machine learning and/or cloud computing services at home or at work in the past 5 years (approximate $USD)?',
 'Q31': 'Which of the following cloud computing platforms do you use?',
 'Q32': 'Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?',
 'Q33': 'Do you use any of the following cloud computing products?',
 'Q34': 'Do you use any of the following data storage products?',
 'Q35': 'Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?',
 'Q36': 'Do you use any of the following business intelligence tools?',
 'Q37': 'Do you use any of the following managed machine learning products on a regular basis?',
 'Q38': 'Do you use any of the following automated machine learning tools?',
 'Q39': 'Do you use any of the following products to serve your machine learning models?',
 'Q40': 'Do you use any tools to help monitor your machine learning models and/or experiments?',
 'Q41': 'Do you use any of the following responsible or ethical AI products in your machine learning practices?',
 'Q42': 'Do you use any of the following types of specialized hardware when training machine learning models?',
 'Q43': 'Approximately how many times have you used a TPU (tensor processing unit)?',
 'Q44': 'Who/what are your favorite media sources that report on data science topics?'}

Vì mục đích của nhóm là phân tích ở 4 quốc giá là **Japan, China, South Korea, Viet Nam** nên sẽ chỉ lấy dưng dòng thuộc 4 quốc gia này.

In [7]:
df_1 = df_1[(df_1['Q4'] == "Japan") | (df_1['Q4'] == "China") | (df_1['Q4'] == "South Korea") | (df_1['Q4'] == "Viet Nam")]
df_1.head(5)

,Duration (in seconds),Q2,Q3,Q4,Q5,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,...,Q44_3,Q44_4,Q44_5,Q44_6,Q44_7,Q44_8,Q44_9,Q44_10,Q44_11,Q44_12
11,470,55-59,Man,South Korea,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,174,25-29,Woman,China,Yes,NaN,NaN,Kaggle Learn Courses,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,506,25-29,Man,Japan,No,NaN,NaN,NaN,NaN,NaN,...,NaN,"Kaggle (notebooks, forums, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,283,22-24,Woman,China,Yes,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
72,492,40-44,Man,Japan,No,NaN,NaN,Kaggle Learn Courses,NaN,NaN,...,NaN,"Kaggle (notebooks, forums, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_1 = df_1[(df_1['Q4'] == "Japan")]
df_1.head(5)

,Duration (in seconds),Q2,Q3,Q4,Q5,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,...,Q44_3,Q44_4,Q44_5,Q44_6,Q44_7,Q44_8,Q44_9,Q44_10,Q44_11,Q44_12
36,506,25-29,Man,Japan,No,NaN,NaN,NaN,NaN,NaN,...,NaN,"Kaggle (notebooks, forums, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,492,40-44,Man,Japan,No,NaN,NaN,Kaggle Learn Courses,NaN,NaN,...,NaN,"Kaggle (notebooks, forums, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,985,30-34,Man,Japan,No,NaN,NaN,NaN,NaN,NaN,...,NaN,"Kaggle (notebooks, forums, etc)",NaN,NaN,NaN,"Blogs (Towards Data Science, Analytics Vidhya,...","Journal Publications (peer-reviewed journals, ...","Slack Communities (ods.ai, kagglenoobs, etc)",NaN,NaN
124,883,30-34,Man,Japan,No,NaN,NaN,NaN,NaN,NaN,...,NaN,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...",NaN,NaN,NaN,"Slack Communities (ods.ai, kagglenoobs, etc)",NaN,NaN
139,417,22-24,Man,Japan,Yes,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columnss có 2 dạng, loại 1 là câu hỏi trả lời đáp án, loại 2 là những câu hỏi _1, _2, ... là dạng catogerial nên sẽ chọn những câu loại 1 lưu trước vào `df`.

In [9]:
col = df_1.columns
newcol = []
for i in col:
    if '_' not in i:
        newcol.append(i)

In [10]:
df = df_1[newcol]
df.head(5)

,Duration (in seconds),Q2,Q3,Q4,Q5,Q8,Q9,Q11,Q16,Q22,Q23,Q24,Q25,Q26,Q27,Q29,Q30,Q32,Q43
36,506,25-29,Man,Japan,No,Master’s degree,No,3-5 years,2-3 years,NaN,Data Scientist,Computers/Technology,"1000-9,999 employees",1-2,"We recently started using ML methods (i.e., mo...","50,000-59,999",$100-$999,NaN,Never
72,492,40-44,Man,Japan,No,No formal education past high school,NaN,< 1 years,I do not use machine learning methods,NaN,Other,Manufacturing/Fabrication,"1000-9,999 employees",0,I do not know,"50,000-59,999","$10,000-$99,999",NaN,NaN
84,985,30-34,Man,Japan,No,Master’s degree,Yes,5-10 years,3-4 years,Huggingface Models,Software Engineer,Manufacturing/Fabrication,"10,000 or more employees",3-4,We are exploring ML methods (and may one day p...,$0-999,$100-$999,Amazon Web Services (AWS),Once
124,883,30-34,Man,Japan,No,Master’s degree,No,3-5 years,3-4 years,Kaggle datasets,Data Scientist,Insurance/Risk Assessment,"1000-9,999 employees",5-9,We are exploring ML methods (and may one day p...,"4,000-4,999",$100-$999,They all had a similarly enjoyable developer e...,2-5 times
139,417,22-24,Man,Japan,Yes,Bachelor’s degree,NaN,1-3 years,2-3 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Tiếp đến, ta sẽ xử lý những câu hỏi loại 2 và tiếp tục lưu nó vào `df`

In [11]:
for i in range(len(col)):
    ij = col[i] + ' ' 
    if '_1 ' in ij:
        arr = [elem for elem in col if elem.startswith(col[i][0:col[i].index("_")])]
        temp_df = df_1[arr]
        a = [tuple(filter(lambda x: pd.notnull(x), row)) for row in temp_df.values]
        df[col[i][0:col[i].index("_")]] = a
df = df.applymap(lambda x: np.nan if isinstance(x, tuple) and len(x) == 0 else x)

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a
C:\Users\ADMIN\AppData\Local\Temp/ipykernel_22328/3130294925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col[i][0:col[i].index("_")]] = a

Vì name của columns đang ở dạng Q1, Q2, ... nên ta sẽ chuyển thành câu hỏi và reindex để dữ liệu dễ phân tích hơn.

In [12]:
sort_col = ['Duration (in seconds)']
for i in range(2,45):
    sort_col.append('Q' + str(i))
df = df.reindex(columns=sort_col)
df = df.reset_index(drop=True)
df.rename(columns=new_dic, inplace = True)
df.index = df.index + 1
df

,Duration,What is your age (# years)?,What is your gender?,In which country do you currently reside?,Are you currently a student?,On which platforms have you begun or completed data science courses?,What products or platforms did you find to be most helpful when you first started studying data science?,What is the highest level of formal education that you have attained or plan to attain within the next 2 years?,"Have you ever published any academic research (papers, preprints, conference proceedings, etc)?",Did your research make use of machine learning?,...,"Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?",Do you use any of the following business intelligence tools?,Do you use any of the following managed machine learning products on a regular basis?,Do you use any of the following automated machine learning tools?,Do you use any of the following products to serve your machine learning models?,Do you use any tools to help monitor your machine learning models and/or experiments?,Do you use any of the following responsible or ethical AI products in your machine learning practices?,Do you use any of the following types of specialized hardware when training machine learning models?,Approximately how many times have you used a TPU (tensor processing unit)?,Who/what are your favorite media sources that report on data science topics?
1,506,25-29,Man,Japan,No,"(Udemy,)","(Online courses (Coursera, EdX, etc),)",Master’s degree,No,NaN,...,"(None,)","(None,)","(No / None,)","(No / None,)","(None,)","( Weights & Biases ,)","(None,)","( GPUs ,)",Never,"(Kaggle (notebooks, forums, etc),)"
2,492,40-44,Man,Japan,No,"(Kaggle Learn Courses,)","(Video platforms (YouTube, Twitch, etc), Kaggl...",No formal education past high school,NaN,NaN,...,"(None,)","(None,)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Kaggle (notebooks, forums, etc),)"
3,985,30-34,Man,Japan,No,(University Courses (resulting in a university...,"(University courses, Kaggle (notebooks, compet...",Master’s degree,Yes,"(No,)",...,"(SQLite , Oracle Database , IBM Db2 , Amazon R...","(Microsoft Power BI,)","( Amazon SageMaker , Google Cloud Vertex AI)","( Amazon Sagemaker Autopilot ,)","( MLflow ,)","( MLflow ,)","( Amazon AI Ethics Tools (Clarify, A2I, etc) ,)","( GPUs ,)",Once,"(Twitter (data science influencers), Email new..."
4,883,30-34,Man,Japan,No,(Cloud-certification programs (direct from AWS...,"(Video platforms (YouTube, Twitch, etc),)",Master’s degree,No,NaN,...,"(MySQL , PostgreSQL , Oracle Database , Micros...","(Google Data Studio, Tableau)","( Databricks, Dataiku)","( Google Cloud AutoML ,)","( ONNX Runtime , OpenVINO Model Server )","( Weights & Biases , MLflow )","( Google Responsible AI Toolkit (LIT, What-if,...","( GPUs ,)",2-5 times,"(Email newsletters (Data Elixir, O'Reilly Data..."
5,417,22-24,Man,Japan,Yes,"(None,)","(Other,)",Bachelor’s degree,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Twitter (data science influencers),)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,1289,50-54,Man,Japan,No,"(None,)","(Social media platforms (Reddit, Twitter, etc)...",I prefer not to answer,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Twitter (data science influencers), Kaggle (n..."
553,695,35-39,Man,Japan,No,"(None,)","(Kaggle (notebooks, competitions, etc),)",Doctoral degree,Yes,"(No,)",...,"(SQLite ,)","(None,)","(No / None,)","(No / None,)","(None,)","(No / None,)","(None,)","(None,)",Never,"(Kaggle (notebooks, forums, etc),)"
554,156,45-49,Man,Japan,No,"(Kaggle Learn Courses,)","(Social media platforms (Reddit, Twitter, etc),)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
555,43922,18-21,Man,Japan,Yes,(University Courses (resulting in a university...,"(Online courses (Coursera, EdX, etc),)",Bachelor’s degree,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556,617,50-54,Man,Japan,No,"(None,)","(Kaggle (notebooks, competitions, etc),)",I prefer not to answer,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Dữ liệu có bao nhiêu dòng và bao nhiêu cột

In [13]:
df.shape

(556, 44)

Dữ liệu có 1538 dòng và 44 cột.

### Mỗi dòng có ý nghĩa gì? Có vấn đề các dòng có ý nghĩa khác nhau không?

Ta sẽ xem thử rằng trong tập có dòng nào bị trùng không. Nếu trùng thì trả về True, không thì là False và lưu số dòng trùng vào biến num_duplicated_rows

In [14]:
#Tính tổng dòng lặp
num_duplicated_rows = df.duplicated().sum()
is_duplicated = (num_duplicated_rows != 0)
print('So dong lap la {}'.format(num_duplicated_rows))
if is_duplicated == False:
    print('Bo du lieu khong lap')

So dong lap la 0
Bo du lieu khong lap

Vậy không có dòng lặp trong bộ dữ liệu này

### Mỗi cột có ý nghĩa gì?

In [15]:
df.columns

Index(['Duration', 'What is your age (# years)?', 'What is your gender?',
       'In which country do you currently reside?',
       'Are you currently a student?',
       'On which platforms have you begun or completed data science courses?',
       'What products or platforms did you find to be most helpful when you first started studying data science?',
       'What is the highest level of formal education that you have attained or plan to attain within the next 2 years?',
       'Have you ever published any academic research (papers, preprints, conference proceedings, etc)?',
       'Did your research make use of machine learning?',
       'For how many years have you been writing code and/or programming?',
       'What programming languages do you use on a regular basis?',
       'Which of the following integrated development environments (IDE's) do you use on a regular basis?',
       'Do you use any of the following hosted notebook products?',
       'Do you use any of the following data visualization libraries on a regular basis?',
       'For how many years have you used machine learning methods?',
       'Which of the following machine learning frameworks do you use on a regular basis?',
       'Which of the following ML algorithms do you use on a regular basis?',
       'Which categories of computer vision methods do you use on a regular basis?',
       'Which of the following natural language processing (NLP) methods do you use on a regular basis?',
       'Do you download pre-trained model weights from any of the following services?',
       'Which of the following ML model hubs/repositories do you use most often?',
       'Select the title most similar to your current role (or most recent title if retired)',
       'In what industry is your current employer/contract (or your most recent employer if retired)?',
       'What is the size of the company where you are employed?',
       'Approximately how many individuals are responsible for data science workloads at your place of business?',
       'Does your current employer incorporate machine learning methods into their business?',
       'Select any activities that make up an important part of your role at work',
       'What is your current yearly compensation (approximate $USD)?',
       'Approximately how much money have you spent on machine learning and/or cloud computing services at home or at work in the past 5 years (approximate $USD)?',
       'Which of the following cloud computing platforms do you use?',
       'Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?',
       'Do you use any of the following cloud computing products?',
       'Do you use any of the following data storage products?',
       'Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?',
       'Do you use any of the following business intelligence tools?',
       'Do you use any of the following managed machine learning products on a regular basis?',
       'Do you use any of the following automated machine learning tools?',
       'Do you use any of the following products to serve your machine learning models?',
       'Do you use any tools to help monitor your machine learning models and/or experiments?',
       'Do you use any of the following responsible or ethical AI products in your machine learning practices?',
       'Do you use any of the following types of specialized hardware when training machine learning models?',
       'Approximately how many times have you used a TPU (tensor processing unit)?',
       'Who/what are your favorite media sources that report on data science topics?'],
      dtype='object')

Ý nghĩa của mỗi cột là:

- **Duration** là thời gian(s)  thực hiện khảo sát.

- Các cột còn lại là câu hỏi khảo sát. Và giá trị của các cột là câu trả lời.

Ta kiểm tra dạng dữ liệu của các cột để xem có đúng với dạng mà ta mong muốn không.

In [16]:
df.dtypes

Duration                                                                                                                                                      object
What is your age (# years)?                                                                                                                                   object
What is your gender?                                                                                                                                          object
In which country do you currently reside?                                                                                                                     object
Are you currently a student?                                                                                                                                  object
On which platforms have you begun or completed data science courses?                                                                                          object
What products or platforms did you find to be most helpful when you first started studying data science?                                                      object
What is the highest level of formal education that you have attained or plan to attain within the next 2 years?                                               object
Have you ever published any academic research (papers, preprints, conference proceedings, etc)?                                                               object
Did your research make use of machine learning?                                                                                                               object
For how many years have you been writing code and/or programming?                                                                                             object
What programming languages do you use on a regular basis?                                                                                                     object
Which of the following integrated development environments (IDE's) do you use on a regular basis?                                                             object
Do you use any of the following hosted notebook products?                                                                                                     object
Do you use any of the following data visualization libraries on a regular basis?                                                                              object
For how many years have you used machine learning methods?                                                                                                    object
Which of the following machine learning frameworks do you use on a regular basis?                                                                             object
Which of the following ML algorithms do you use on a regular basis?                                                                                           object
Which categories of computer vision methods do you use on a regular basis?                                                                                    object
Which of the following natural language processing (NLP) methods do you use on a regular basis?                                                               object
Do you download pre-trained model weights from any of the following services?                                                                                 object
Which of the following ML model hubs/repositories do you use most often?                                                                                      object
Select the title most similar to your current role (or most recent title if retired)                                                                          object
In what industry is your current employer/contract (or your most recent employer if retired)?                                                                 object
What is the size of the company where you are employed?                                                                                                       object
Approximately how many individuals are responsible for data science workloads at your place of business?                                                      object
Does your current employer incorporate machine learning methods into their business?                                                                          object
Select any activities that make up an important part of your role at work                                                                                     object
What is your current yearly compensation (approximate $USD)?                                                                                                  object
Approximately how much money have you spent on machine learning and/or cloud computing services at home or at work in the past 5 years (approximate $USD)?    object
Which of the following cloud computing platforms do you use?                                                                                                  object
Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?                                           object
Do you use any of the following cloud computing products?                                                                                                     object
Do you use any of the following data storage products?                                                                                                        object
Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?                                                object
Do you use any of the following business intelligence tools?                                                                                                  object
Do you use any of the following managed machine learning products on a regular basis?                                                                         object
Do you use any of the following automated machine learning tools?                                                                                             object
Do you use any of the following products to serve your machine learning models?                                                                               object
Do you use any tools to help monitor your machine learning models and/or experiments?                                                                         object
Do you use any of the following responsible or ethical AI products in your machine learning practices?                                                        object
Do you use any of the following types of specialized hardware when training machine learning models?                                                          object
Approximately how many times have you used a TPU (tensor processing unit)?                                                                                    object
Who/what are your favorite media sources that report on data science topics?                                                                                  object
dtype: object

Cột **Duration** đang ở dạng object và sai định dạng. Ta sẽ chuyển nó về dạng số `int64`

In [17]:
df['Duration'] = df['Duration'].astype('int64')

Ta thấy rằng các cột đã có định dạng đúng với định dạng mà ta mong muốn. Gồm 1 cột **Duration** có dạng **int** và toàn bộ cột còn lại có dạng **object**

## XỬ LÝ DỮ LIỆU NAN

Ta xem thử mỗi cột có bao nhiêu dữ liệu nan

In [18]:
df.isnull().sum()

Duration                                                                                                                                                        0
What is your age (# years)?                                                                                                                                     0
What is your gender?                                                                                                                                            0
In which country do you currently reside?                                                                                                                       0
Are you currently a student?                                                                                                                                    0
On which platforms have you begun or completed data science courses?                                                                                            0
What products or platforms did you find to be most helpful when you first started studying data science?                                                       11
What is the highest level of formal education that you have attained or plan to attain within the next 2 years?                                                22
Have you ever published any academic research (papers, preprints, conference proceedings, etc)?                                                               291
Did your research make use of machine learning?                                                                                                               401
For how many years have you been writing code and/or programming?                                                                                              27
What programming languages do you use on a regular basis?                                                                                                      45
Which of the following integrated development environments (IDE's) do you use on a regular basis?                                                              52
Do you use any of the following hosted notebook products?                                                                                                      66
Do you use any of the following data visualization libraries on a regular basis?                                                                               73
For how many years have you used machine learning methods?                                                                                                     77
Which of the following machine learning frameworks do you use on a regular basis?                                                                             121
Which of the following ML algorithms do you use on a regular basis?                                                                                           129
Which categories of computer vision methods do you use on a regular basis?                                                                                    363
Which of the following natural language processing (NLP) methods do you use on a regular basis?                                                               420
Do you download pre-trained model weights from any of the following services?                                                                                 136
Which of the following ML model hubs/repositories do you use most often?                                                                                      437
Select the title most similar to your current role (or most recent title if retired)                                                                          156
In what industry is your current employer/contract (or your most recent employer if retired)?                                                                 186
What is the size of the company where you are employed?                                                                                                       187
Approximately how many individuals are responsible for data science workloads at your place of business?                                                      187
Does your current employer incorporate machine learning methods into their business?                                                                          191
Select any activities that make up an important part of your role at work                                                                                     201
What is your current yearly compensation (approximate $USD)?                                                                                                  223
Approximately how much money have you spent on machine learning and/or cloud computing services at home or at work in the past 5 years (approximate $USD)?    209
Which of the following cloud computing platforms do you use?                                                                                                  282
Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?                                           461
Do you use any of the following cloud computing products?                                                                                                     362
Do you use any of the following data storage products?                                                                                                        362
Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?                                                286
Do you use any of the following business intelligence tools?                                                                                                  288
Do you use any of the following managed machine learning products on a regular basis?                                                                         302
Do you use any of the following automated machine learning tools?                                                                                             302
Do you use any of the following products to serve your machine learning models?                                                                               302
Do you use any tools to help monitor your machine learning models and/or experiments?                                                                         302
Do you use any of the following responsible or ethical AI products in your machine learning practices?                                                        302
Do you use any of the following types of specialized hardware when training machine learning models?                                                          303
Approximately how many times have you used a TPU (tensor processing unit)?                                                                                    304
Who/what are your favorite media sources that report on data science topics?                                                                                  127
dtype: int64

- Với 6 câu hỏi (columns) đầu tiên, ta không thấy xuất hiện giá trị NAN. Có lẽ đây là những câu trả hỏi bắc buộc của khảo sát nên rất đầy đủ giá trị.

- Với các câu hỏi (columns) còn lại, ta thấy xuất hiện rất nhiều giá trị NAN. Vì đây là những câu hỏi tự chọn. Ta sẽ xoá những cột có quá nhiều giá trị NAN vì những cột này sẽ mang lại rất ít thông tin những lại gây khó khăn nhiều trong quá trình phân tích. Với dữ liệu hơn 1500 dòng, ta sẽ xoá những dòng có hơn 500 dòng NAN.

In [19]:
nan_counts = df.isna().sum()

columns_to_drop = nan_counts[nan_counts > 500].index

df.drop(columns=columns_to_drop, inplace= True)
df.isna().sum()

Duration                                                                                                                                                        0
What is your age (# years)?                                                                                                                                     0
What is your gender?                                                                                                                                            0
In which country do you currently reside?                                                                                                                       0
Are you currently a student?                                                                                                                                    0
On which platforms have you begun or completed data science courses?                                                                                            0
What products or platforms did you find to be most helpful when you first started studying data science?                                                       11
What is the highest level of formal education that you have attained or plan to attain within the next 2 years?                                                22
Have you ever published any academic research (papers, preprints, conference proceedings, etc)?                                                               291
Did your research make use of machine learning?                                                                                                               401
For how many years have you been writing code and/or programming?                                                                                              27
What programming languages do you use on a regular basis?                                                                                                      45
Which of the following integrated development environments (IDE's) do you use on a regular basis?                                                              52
Do you use any of the following hosted notebook products?                                                                                                      66
Do you use any of the following data visualization libraries on a regular basis?                                                                               73
For how many years have you used machine learning methods?                                                                                                     77
Which of the following machine learning frameworks do you use on a regular basis?                                                                             121
Which of the following ML algorithms do you use on a regular basis?                                                                                           129
Which categories of computer vision methods do you use on a regular basis?                                                                                    363
Which of the following natural language processing (NLP) methods do you use on a regular basis?                                                               420
Do you download pre-trained model weights from any of the following services?                                                                                 136
Which of the following ML model hubs/repositories do you use most often?                                                                                      437
Select the title most similar to your current role (or most recent title if retired)                                                                          156
In what industry is your current employer/contract (or your most recent employer if retired)?                                                                 186
What is the size of the company where you are employed?                                                                                                       187
Approximately how many individuals are responsible for data science workloads at your place of business?                                                      187
Does your current employer incorporate machine learning methods into their business?                                                                          191
Select any activities that make up an important part of your role at work                                                                                     201
What is your current yearly compensation (approximate $USD)?                                                                                                  223
Approximately how much money have you spent on machine learning and/or cloud computing services at home or at work in the past 5 years (approximate $USD)?    209
Which of the following cloud computing platforms do you use?                                                                                                  282
Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?                                           461
Do you use any of the following cloud computing products?                                                                                                     362
Do you use any of the following data storage products?                                                                                                        362
Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?                                                286
Do you use any of the following business intelligence tools?                                                                                                  288
Do you use any of the following managed machine learning products on a regular basis?                                                                         302
Do you use any of the following automated machine learning tools?                                                                                             302
Do you use any of the following products to serve your machine learning models?                                                                               302
Do you use any tools to help monitor your machine learning models and/or experiments?                                                                         302
Do you use any of the following responsible or ethical AI products in your machine learning practices?                                                        302
Do you use any of the following types of specialized hardware when training machine learning models?                                                          303
Approximately how many times have you used a TPU (tensor processing unit)?                                                                                    304
Who/what are your favorite media sources that report on data science topics?                                                                                  127
dtype: int64

Giờ dữ liệu chỉ còn những cột có ít hơn 500 dòng chứa NAN.

### Sự phân bố của dữ liệu

### Với mỗi cột có kiểu dữ liệu dạng số, các giá trị được phân bố như thế nào?

In [20]:
dtypes = df.dtypes
ind = dtypes[(dtypes == np.int64)].index
ind

Index(['Duration'], dtype='object')

In [21]:
df[ind]

     Duration
1         506
2         492
3         985
4         883
5         417
..        ...
552      1289
553       695
554       156
555     43922
556       617

[556 rows x 1 columns]

Ta có cột dữ liệu dạng số 'Duration'. Ta sẽ tính min, max, mean, median để xem sự phân bố của dữ liệu và có gì bất thường ở các cột này không?

In [22]:
print('Min:', int(df[ind].min()))
print('Max:', int(df[ind].max()))
print('Mean:', int(df[ind].mean()))
print('Median:', int(df[ind].median()))

Min: 120
Max: 2445778
Mean: 21303
Median: 666

Ta thấy các giá trị ở cột này không có gì bất thường

### Với mỗi cột có kiểu dữ liệu không phải dạng số, các giá trị được phân bố như thế nào?

In [23]:
dtypes = df.dtypes
ind = dtypes[(dtypes != np.int64)].index
ind

Index(['What is your age (# years)?', 'What is your gender?',
       'In which country do you currently reside?',
       'Are you currently a student?',
       'On which platforms have you begun or completed data science courses?',
       'What products or platforms did you find to be most helpful when you first started studying data science?',
       'What is the highest level of formal education that you have attained or plan to attain within the next 2 years?',
       'Have you ever published any academic research (papers, preprints, conference proceedings, etc)?',
       'Did your research make use of machine learning?',
       'For how many years have you been writing code and/or programming?',
       'What programming languages do you use on a regular basis?',
       'Which of the following integrated development environments (IDE's) do you use on a regular basis?',
       'Do you use any of the following hosted notebook products?',
       'Do you use any of the following data visualization libraries on a regular basis?',
       'For how many years have you used machine learning methods?',
       'Which of the following machine learning frameworks do you use on a regular basis?',
       'Which of the following ML algorithms do you use on a regular basis?',
       'Which categories of computer vision methods do you use on a regular basis?',
       'Which of the following natural language processing (NLP) methods do you use on a regular basis?',
       'Do you download pre-trained model weights from any of the following services?',
       'Which of the following ML model hubs/repositories do you use most often?',
       'Select the title most similar to your current role (or most recent title if retired)',
       'In what industry is your current employer/contract (or your most recent employer if retired)?',
       'What is the size of the company where you are employed?',
       'Approximately how many individuals are responsible for data science workloads at your place of business?',
       'Does your current employer incorporate machine learning methods into their business?',
       'Select any activities that make up an important part of your role at work',
       'What is your current yearly compensation (approximate $USD)?',
       'Approximately how much money have you spent on machine learning and/or cloud computing services at home or at work in the past 5 years (approximate $USD)?',
       'Which of the following cloud computing platforms do you use?',
       'Of the cloud platforms that you are familiar with, which has the best developer experience (most enjoyable to use)?',
       'Do you use any of the following cloud computing products?',
       'Do you use any of the following data storage products?',
       'Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?',
       'Do you use any of the following business intelligence tools?',
       'Do you use any of the following managed machine learning products on a regular basis?',
       'Do you use any of the following automated machine learning tools?',
       'Do you use any of the following products to serve your machine learning models?',
       'Do you use any tools to help monitor your machine learning models and/or experiments?',
       'Do you use any of the following responsible or ethical AI products in your machine learning practices?',
       'Do you use any of the following types of specialized hardware when training machine learning models?',
       'Approximately how many times have you used a TPU (tensor processing unit)?',
       'Who/what are your favorite media sources that report on data science topics?'],
      dtype='object')

Ta có các cột dữ liệu dạng object như trên. Ta thấy rằng các cột dữ liệu là các câu hỏi lựa chọn. Ta sẽ tính số lượng giá trị, giá trị khác nhau, giá trị xuất hiện nhiều nhất và số lần xuất hiện để xem sự phân bố của dữ liệu và có gì bất thường ở các cột này không?

In [24]:
df[ind].describe()

,What is your age (# years)?,What is your gender?,In which country do you currently reside?,Are you currently a student?,On which platforms have you begun or completed data science courses?,What products or platforms did you find to be most helpful when you first started studying data science?,What is the highest level of formal education that you have attained or plan to attain within the next 2 years?,"Have you ever published any academic research (papers, preprints, conference proceedings, etc)?",Did your research make use of machine learning?,For how many years have you been writing code and/or programming?,...,"Do you use any of the following data products (relational databases, data warehouses, data lakes, or similar)?",Do you use any of the following business intelligence tools?,Do you use any of the following managed machine learning products on a regular basis?,Do you use any of the following automated machine learning tools?,Do you use any of the following products to serve your machine learning models?,Do you use any tools to help monitor your machine learning models and/or experiments?,Do you use any of the following responsible or ethical AI products in your machine learning practices?,Do you use any of the following types of specialized hardware when training machine learning models?,Approximately how many times have you used a TPU (tensor processing unit)?,Who/what are your favorite media sources that report on data science topics?
count,556,556,556,556,556,545,534,265,155,529,...,270,268,254,254,254,254,254,253,252,429
unique,11,4,1,2,73,42,7,2,4,7,...,100,34,27,17,16,17,9,7,5,145
top,40-44,Man,Japan,No,"(None,)","(Kaggle (notebooks, competitions, etc),)",Master’s degree,Yes,"(No,)",1-3 years,...,"(None,)","(None,)","(No / None,)","(No / None,)","(None,)","(No / None,)","(None,)","( GPUs ,)",Never,"(Kaggle (notebooks, forums, etc),)"
freq,79,504,556,470,152,96,191,155,78,113,...,86,153,167,203,204,181,233,132,138,39

Ta thấy không có gì bất thường ở các cột dữ liệu này

Qua quá trình khám phá và tiền xử lý dữ liệu. Ta thấy dữ liệu đã 'sạch' hơn. Ta sẽ lưu vào file `data_science_asia_clean.csv`.

In [25]:
df.to_csv('data_science_asia_clean.csv')

PermissionError: [Errno 13] Permission denied: 'data_science_asia_clean.csv'